server:
  port: 8080
spring:
  profiles:
    active: dev
  redis:
    host: 139.224.255.200
    port: 16379

  datasource:
    druid:
      url: jdbc:mysql://139.224.255.200:13306/ssicp?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: njzlh
      password: njzlh20230411
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 2
      min-idle: 1
      max-active: 5
      test-on-borrow: true
      validation-query: select 1
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        allow: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # Quartz调度器属性
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
            instanceName: clusteredScheduler #quartzScheduler
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore # springboot>2.5.6后使用这个
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #仅为数据库制作了特定于数据库的代理
            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            tablePrefix: qrtz_  #数据库表前缀
            misfireThreshold: 60000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            isClustered: true #打开群集功能
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhilianhua.ssicp.entity.db
  configuration:
    map-underscore-to-camel-case: true

app:
  account:
    root: root
    anonymous: anonymous
    inspectorRoleName: inspector
  file:
    path: D:/files/ssicp

config:
  default:
    password: 123456
  aiModelService:
    url: http://localhost:8081

# InfluxDB 3连接配置
influxdb:
  # InfluxDB 3的API地址
  url: http://139.224.255.200:18086
  # 替换为你的InfluxDB 3的认证Token
  token: hNKI3URC0Tdp3--vrjr4hfr3V-4s8klVek25xxYMO5bb6FxuNDHgGPwr3C9Oj0IysnCWQK0-UQwq1bgH0-mIxQ==
  # 替换为你的组织名称
  org: zhilianhua
  bucket: ssicp